services:
  src-asm:
    build: .
    ports:
      - "8080:5000"
    container_name: src-asm
  tunnel:
    profiles:
      - staging
    volumes:
      - ./cloudflare-tunnel-config.yml:/etc/cloudflared/config.yml  # The minimal config file with protocol
    container_name: src-asm-cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    # ask david for this file it will not be added to git
    env_file: cloudflare-tunnel-secret.env
